
// This file has been generated by the GUI designer. Do not modify.
namespace LongoMatch.Gui.Component
{
	public partial class CategoriesFilter
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget LongoMatch.Gui.Component.CategoriesFilter
			global::Stetic.BinContainer.Attach (this);
			this.Name = "LongoMatch.Gui.Component.CategoriesFilter";
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
