
// This file has been generated by the GUI designer. Do not modify.
namespace LongoMatch.Gui.Component
{
	public partial class PlaysSelectionWidget
	{
		private global::Gtk.Notebook notebook1;
		private global::LongoMatch.Gui.Component.PlaysListTreeWidget playsList;
		private global::Gtk.Label playsList1;
		private global::LongoMatch.Gui.Component.PlayersListTreeWidget localPlayersList;
		private global::Gtk.Label localPlaysList;
		private global::LongoMatch.Gui.Component.PlayersListTreeWidget visitorPlayersList;
		private global::Gtk.Label visitorPlaysList;
		private global::LongoMatch.Gui.Component.PlayersFilter playersfilter;
		private global::Gtk.Label label4;
		private global::LongoMatch.Gui.Component.CategoriesFilter categoriesfilter;
		private global::Gtk.Label label5;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget LongoMatch.Gui.Component.PlaysSelectionWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "LongoMatch.Gui.Component.PlaysSelectionWidget";
			// Container child LongoMatch.Gui.Component.PlaysSelectionWidget.Gtk.Container+ContainerChild
			this.notebook1 = new global::Gtk.Notebook ();
			this.notebook1.CanFocus = true;
			this.notebook1.Name = "notebook1";
			this.notebook1.CurrentPage = 4;
			this.notebook1.TabPos = ((global::Gtk.PositionType)(3));
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.playsList = new global::LongoMatch.Gui.Component.PlaysListTreeWidget ();
			this.playsList.Events = ((global::Gdk.EventMask)(256));
			this.playsList.Name = "playsList";
			this.notebook1.Add (this.playsList);
			// Notebook tab
			this.playsList1 = new global::Gtk.Label ();
			this.playsList1.Name = "playsList1";
			this.playsList1.LabelProp = global::Mono.Unix.Catalog.GetString ("Plays");
			this.notebook1.SetTabLabel (this.playsList, this.playsList1);
			this.playsList1.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.localPlayersList = new global::LongoMatch.Gui.Component.PlayersListTreeWidget ();
			this.localPlayersList.Events = ((global::Gdk.EventMask)(256));
			this.localPlayersList.Name = "localPlayersList";
			this.notebook1.Add (this.localPlayersList);
			global::Gtk.Notebook.NotebookChild w2 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.localPlayersList]));
			w2.Position = 1;
			// Notebook tab
			this.localPlaysList = new global::Gtk.Label ();
			this.localPlaysList.Name = "localPlaysList";
			this.notebook1.SetTabLabel (this.localPlayersList, this.localPlaysList);
			this.localPlaysList.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.visitorPlayersList = new global::LongoMatch.Gui.Component.PlayersListTreeWidget ();
			this.visitorPlayersList.Events = ((global::Gdk.EventMask)(256));
			this.visitorPlayersList.Name = "visitorPlayersList";
			this.notebook1.Add (this.visitorPlayersList);
			global::Gtk.Notebook.NotebookChild w3 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.visitorPlayersList]));
			w3.Position = 2;
			// Notebook tab
			this.visitorPlaysList = new global::Gtk.Label ();
			this.visitorPlaysList.Name = "visitorPlaysList";
			this.notebook1.SetTabLabel (this.visitorPlayersList, this.visitorPlaysList);
			this.visitorPlaysList.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.playersfilter = new global::LongoMatch.Gui.Component.PlayersFilter ();
			this.playersfilter.Events = ((global::Gdk.EventMask)(256));
			this.playersfilter.Name = "playersfilter";
			this.notebook1.Add (this.playersfilter);
			global::Gtk.Notebook.NotebookChild w4 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.playersfilter]));
			w4.Position = 3;
			// Notebook tab
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Players filter");
			this.notebook1.SetTabLabel (this.playersfilter, this.label4);
			this.label4.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.categoriesfilter = new global::LongoMatch.Gui.Component.CategoriesFilter ();
			this.categoriesfilter.Events = ((global::Gdk.EventMask)(256));
			this.categoriesfilter.Name = "categoriesfilter";
			this.notebook1.Add (this.categoriesfilter);
			global::Gtk.Notebook.NotebookChild w5 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.categoriesfilter]));
			w5.Position = 4;
			// Notebook tab
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Categories filter");
			this.notebook1.SetTabLabel (this.categoriesfilter, this.label5);
			this.label5.ShowAll ();
			this.Add (this.notebook1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
