
// This file has been generated by the GUI designer. Do not modify.
namespace LongoMatch.Gui.Component
{
	public partial class PlaysSelectionWidget
	{
		private global::Gtk.Notebook notebook1;
		private global::LongoMatch.Gui.Component.PlaysListTreeWidget playsList;
		private global::Gtk.Label playsList1;
		private global::LongoMatch.Gui.Component.PlayersListTreeWidget localPlayersList;
		private global::Gtk.Label localPlaysList;
		private global::LongoMatch.Gui.Component.PlayersListTreeWidget visitorPlayersList;
		private global::Gtk.Label visitorPlaysList;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget LongoMatch.Gui.Component.PlaysSelectionWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "LongoMatch.Gui.Component.PlaysSelectionWidget";
			// Container child LongoMatch.Gui.Component.PlaysSelectionWidget.Gtk.Container+ContainerChild
			this.notebook1 = new global::Gtk.Notebook ();
			this.notebook1.CanFocus = true;
			this.notebook1.Name = "notebook1";
			this.notebook1.CurrentPage = 2;
			this.notebook1.TabPos = ((global::Gtk.PositionType)(3));
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.playsList = new global::LongoMatch.Gui.Component.PlaysListTreeWidget ();
			this.playsList.Events = ((global::Gdk.EventMask)(256));
			this.playsList.Name = "playsList";
			this.notebook1.Add (this.playsList);
			// Notebook tab
			this.playsList1 = new global::Gtk.Label ();
			this.playsList1.Name = "playsList1";
			this.playsList1.LabelProp = global::Mono.Unix.Catalog.GetString ("Plays");
			this.notebook1.SetTabLabel (this.playsList, this.playsList1);
			this.playsList1.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.localPlayersList = new global::LongoMatch.Gui.Component.PlayersListTreeWidget ();
			this.localPlayersList.Events = ((global::Gdk.EventMask)(256));
			this.localPlayersList.Name = "localPlayersList";
			this.notebook1.Add (this.localPlayersList);
			global::Gtk.Notebook.NotebookChild w2 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.localPlayersList]));
			w2.Position = 1;
			// Notebook tab
			this.localPlaysList = new global::Gtk.Label ();
			this.localPlaysList.Name = "localPlaysList";
			this.notebook1.SetTabLabel (this.localPlayersList, this.localPlaysList);
			this.localPlaysList.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.visitorPlayersList = new global::LongoMatch.Gui.Component.PlayersListTreeWidget ();
			this.visitorPlayersList.Events = ((global::Gdk.EventMask)(256));
			this.visitorPlayersList.Name = "visitorPlayersList";
			this.notebook1.Add (this.visitorPlayersList);
			global::Gtk.Notebook.NotebookChild w3 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.visitorPlayersList]));
			w3.Position = 2;
			// Notebook tab
			this.visitorPlaysList = new global::Gtk.Label ();
			this.visitorPlaysList.Name = "visitorPlaysList";
			this.notebook1.SetTabLabel (this.visitorPlayersList, this.visitorPlaysList);
			this.visitorPlaysList.ShowAll ();
			this.Add (this.notebook1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
